// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T1_Wormhole_2._0._1.Models.Database;

public partial class ObtainStatus
{
    /// <summary>
    /// 稱號ID
    /// </summary>
    public int ObtainId { get; set; }

    /// <summary>
    /// 使用者ID
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// 稱號獲得時間
    /// </summary>
    public DateTime Time { get; set; }

    /// <summary>
    /// 稱號數量
    /// </summary>
    public int Count { get; set; }

    public string Status { get; set; }

    public virtual Obtain Obtain { get; set; }

    public virtual UserInfo User { get; set; }
}